name: Tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            - ~/.m2/repository
            - ~/.gitlibs
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Start services
        run: docker compose up --detach

      - name: Run tests
        run: clojure -X:dev user/transcribe

      - name: Stop services
        run: docker compose down --volumes --remove-orphans
